# Install dependencies only when needed
FROM node:20-alpine AS deps
ENV TZ=America/El_Salvador
# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
RUN apk add --no-cache libc6-compat
WORKDIR /usr/src/app
COPY package.json yarn.lock ./
RUN yarn install   
COPY . .
COPY prisma ./prisma/
RUN npx prisma generate 
CMD [ "yarn","start:dev" ] 