
version: '3.1'

services:  
  # nestjsapp:
  #   depends_on:
  #     - db-facial
  #   # build: 
  #   #   context: .
  #   #   dockerfile: Dockerfile
  #   #image: nestjs-docker
  #   image: localhost/marcacion-backend
  #   container_name: nestjsapp
  #   restart: always # reiniciar el contenedor si se detiene
  #   ports:
  #     - "${PORT}:${PORT}"  
  #   env_file: .env
  #   networks:
  #     - network-mar 
  #   volumes: 
  #     - volumen_db:/usr/src/app/uploads
  #     - volumen_db_temp:/usr/src/app/uploads_temp 
    

  db-facial:
    image: postgres:15.2-alpine
    container_name: ${DB_HOST}
    restart: always
    ports:
      - 5435:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      TZ: 'America/El_Salvador'
      PGTZ: 'America/El_Salvador'
    networks:
      - network-mar

networks:
  network-mar:
    external: true
 
volumes:
  volumen_db:
    external: true
  volumen_db_temp:
    external: true
      